const CONSTANTS = {

    //Components to be Rendered 
    RENDER_LOGIN_FORM: 1,
    RENDER_SIGNUP_FORM: 2,
    RENDER_SET_EMAIL_FORM: 3,
    RENDER_HOME_PRODUCTS_PAGE: 4,
    RENDER_PERSON_DEATILS_FORM: 5,
    RENDER_EMPLOYER_DETAILS_FORM: 6,
    RENDER_EXPERIENCE_FORM: 7,
    RENDER_SOFT_APPROVAL_FORM: 8,
    RENDER_INCOME_PROOF_PAGE: 9,
    RENDER_DISBURSMENTOVERVIEW_PAGE: 10,
    RENDER_PASSPORT_PHOTO: 11,
    RENDER_AADHAR: 12,
    RENDER_BACKDROP: 14,
    VALIDATION_CONSTANTS: {
        EMAIL: 1,
        PAN: 2,
        FULLNAME : 3,
        PINCODE: 4, 
        SALARY:5,
    },


    //Event Handling Constants 
    ENTER_PRESSED: 13



}
export default CONSTANTS;